/data/logs/*.log {
    daily
    rotate 365
    dateext
    dateformat -%Y%m%d
    copytruncate
    nocompress
    missingok
    notifempty
    lastaction
        find /data/logs -maxdepth 1 -type f \( -name "*.log-*" -o -name "*.log.*" \) ! -name "*.gz" -mmin +4320 -exec gzip -9 {} \;
        find /data/logs -maxdepth 1 -type f \( -name "*.log-*.gz" -o -name "*.log.*.gz" \) -mtime +365 -delete
    endscript
}
